export {Chat} from '@styled-icons/boxicons-regular/index'
export {DotsVerticalRounded} from 'styled-icons/boxicons-regular/index'
export {Search} from 'styled-icons/boxicons-regular/index'
export {Microphone} from 'styled-icons/boxicons-solid/index'
export {Paperclip} from 'styled-icons/feather/index'
export {InsertEmoticon} from 'styled-icons/material/index'
export {AmpStories} from 'styled-icons/material-rounded/index'
export {KeyboardArrowDown} from 'styled-icons/material-sharp/index'